# Generated by Django 3.1.6 on 2021-02-14 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210214_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_list',
            new_name='image',
        ),
    ]
